Repository ss-dev-x/ees-clean, pull requests merged in 2024-01, with the labels that each got.

#5 Develop
  Application/Features/SU/SURT05/Create.cs
  Application/Features/SU/SURT05/Delete.cs
  Application/Features/SU/SURT05/Detail.cs
  Application/Features/SU/SURT05/Edit.cs
  Application/Features/SU/SURT05/List.cs
  Domain/Entities/SU/Message.cs
  Persistense/Configurations/SU/MessageConfiguration.cs
  Web/ClientApp/src/app/feature/su/su-routing.module.ts
  Web/ClientApp/src/app/feature/su/su.module.ts
  Web/ClientApp/src/app/feature/su/surt05/surt05-detail/surt05-detail.component.html
  Web/ClientApp/src/app/feature/su/surt05/surt05-detail/surt05-detail.component.ts
  Web/ClientApp/src/app/feature/su/surt05/surt05.component.ts
  Web/ClientApp/src/app/feature/su/surt05/surt05.resolver.ts
  Web/ClientApp/src/app/feature/su/surt05/surt05.service.ts
  Web/ClientApp/src/app/models/su/message.ts
  Web/Controllers/SU/Surt05Controller.cs
Labels: bug

#2 [DBRT01] : List page success
  Application/Features/DB/DBRT01/Delete.cs
  Application/Features/DB/DBRT01/Detail.cs
  Application/Features/DB/DBRT01/List.cs
  Application/Features/DB/DBRT01/Save.cs
  Domain/Entities/DB/Status.cs
  Persistense/Configurations/DB/DbDbContext.cs
  Persistense/Configurations/DB/StatusConfigurations.cs
  Web/ClientApp/src/app/app-routing.module.ts
  Web/ClientApp/src/app/feature/db/db-routing.module.ts
  Web/ClientApp/src/app/feature/db/db.module.ts
  Web/ClientApp/src/app/feature/db/dbrt01/dbrt01-detail/dbrt01-detail.component.html
  Web/ClientApp/src/app/feature/db/dbrt01/dbrt01-detail/dbrt01-detail.component.ts
  Web/ClientApp/src/app/feature/db/dbrt01/dbrt01.component.html
  Web/ClientApp/src/app/feature/db/dbrt01/dbrt01.component.ts
  Web/ClientApp/src/app/feature/db/dbrt01/dbrt01.resolver.ts
  Web/ClientApp/src/app/feature/db/dbrt01/dbrt01.service.ts
  Web/ClientApp/src/app/models/db/status.ts
  Web/Controllers/DB/Dbrt01Controller.cs
Labels: bug, feature

#6 [SURT06] : Finish feature
  Application/Features/SU/SURT06/Delete.cs
  Application/Features/SU/SURT06/Detail.cs
  Application/Features/SU/SURT06/List.cs
  Application/Features/SU/SURT06/Save.cs
  Persistense/Configurations/SU/SuDbContext.cs
  Web/ClientApp/src/app/feature/su/su-routing.module.ts
  Web/ClientApp/src/app/feature/su/su.module.ts
  Web/ClientApp/src/app/feature/su/surt06/surt06-detail/surt06-detail.component.html
  Web/ClientApp/src/app/feature/su/surt06/surt06-detail/surt06-detail.component.ts
  Web/ClientApp/src/app/feature/su/surt06/surt06.component.html
  Web/ClientApp/src/app/feature/su/surt06/surt06.component.ts
  Web/ClientApp/src/app/feature/su/surt06/surt06.resolver.ts
  Web/ClientApp/src/app/feature/su/surt06/surt06.service.ts
  Web/Controllers/SU/Surt06Controller.cs
Labels: feature
